### ISSUE TITLE
[React Native, Expo] UI elements slide up when keyboard opens?

### ISSUE THREAD

**Issue by FostersData** [papercups-io/chat-widget#104]
Encountered this somewhat puzzling UI behaviour: when you start typing and the keyboard slides up, the header and previous messages slide up out of view too?
Would be great to keep as much context as possible for the user - is there a way to do this? 

Note this is in React Native on iOS with Expo.

Before:
<img src="https://user-images.githubusercontent.com/68621265/130164973-88c7bb6e-212c-4501-8c77-f68aad24dddf.jpg" width="200">

After:
<img src="https://user-images.githubusercontent.com/68621265/130164984-cb03d792-10e9-4876-9a31-aac6a1192b1b.jpg" width="200">

**Comment by reichert621** [comment]
hey @FostersData! what kind of iOS device is this on?

**Comment by reichert621** [comment]
also do you mind posting this in the https://github.com/papercups-io/chat-widget-native repo?

**Comment by FostersData** [comment]
@reichert621  sure, I've made an issue [here](https://github.com/papercups-io/chat-widget-native/issues/9)

**Comment by reichert621** [comment]
thanks!
