### ISSUE TITLE
Please make placeholder "Start typing..." customisable 

### ISSUE THREAD

**Issue by webdeb** [papercups-io/chat-widget#16]
Hello, I really like the papercups.
Would love if the placeholder could be a customisable for i18n.

**Comment by reichert621** [comment]
great idea @webdeb! happy to make that change

**Comment by BonneauPhilippe** [comment]
I need this too. My site is in French

**Comment by reichert621** [comment]
@BonneauPhilippe I'll add it today :) just focusing on moving the chat window into an iframe first 👍

**Comment by BonneauPhilippe** [comment]
Hi Alex. Thank you for your quickness. I have put the code in a Raw content element in the header of my Wordpress Theme (Themeco Pro). Here is the result https://dev.ecordl.ca

Philippe


 <http://ecommunication.ca/>
Philippe Bonneau

68, route 132

Saint-Germain

G0L 3G0 

581 729-1502
philippe@ecommunication.ca <mailto:philippe@ecommunication.ca> 
Web: ecommunication.ca <http://ecommunication.ca/>
Facebook: ecommunication.kamouraska
 <https://www.facebook.com/ecommunication.kamouraska/>Twitter: eco_mmunication <https://twitter.com/eco_mmunication>
 <https://www.facebook.com/ecommunication.kamouraska/>LinkedIn: philippebonneau <https://ca.linkedin.com/in/philippebonneau>
Skype: philippebonneau

**Comment by reichert621** [comment]
@BonneauPhilippe hmm I can't seem to view https://dev.ecordl.ca -- I might not have permission? it's redirecting me to https://ecordl.ca/

can you take a screenshot? is it still not working?

**Comment by BonneauPhilippe** [comment]
Sorry Alex. I have moved this feature to a dev environment here https://dev.ecordl.ca
 <http://ecommunication.ca/>
Philippe Bonneau

68, route 132

Saint-Germain

G0L 3G0 

581 729-1502
philippe@ecommunication.ca <mailto:philippe@ecommunication.ca> 
Web: ecommunication.ca <http://ecommunication.ca/>
Facebook: ecommunication.kamouraska
 <https://www.facebook.com/ecommunication.kamouraska/>Twitter: eco_mmunication <https://twitter.com/eco_mmunication>
 <https://www.facebook.com/ecommunication.kamouraska/>LinkedIn: philippebonneau <https://ca.linkedin.com/in/philippebonneau>
Skype: philippebonneau

**Comment by reichert621** [comment]
@BonneauPhilippe I'm afraid I can't access this url https://dev.ecordl.ca 😞

**Comment by BonneauPhilippe** [comment]
Hi Alex Sorry for the delay. There was a problem with the .htaccess file. You should be able to access the provided link now.

Bonne journée.

Philippe
 <http://ecommunication.ca/>
Philippe Bonneau

68, route 132

Saint-Germain

G0L 3G0 

581 729-1502
philippe@ecommunication.ca <mailto:philippe@ecommunication.ca> 
Web: ecommunication.ca <http://ecommunication.ca/>
Facebook: ecommunication.kamouraska
 <https://www.facebook.com/ecommunication.kamouraska/>Twitter: eco_mmunication <https://twitter.com/eco_mmunication>
 <https://www.facebook.com/ecommunication.kamouraska/>LinkedIn: philippebonneau <https://ca.linkedin.com/in/philippebonneau>
Skype: philippebonneau

**Comment by reichert621** [comment]
@BonneauPhilippe  @webdeb you should now be able to customize this:

**in HTML:**
```html
<script>
  window.Papercups = {
    config: {
      // ... 
      newMessagePlaceholder: 'Customize me!', // "Start typing..." by default
      // ... 
    },
  };
</script>
<script
  type="text/javascript"
  async
  defer
  src="https://app.papercups.io/widget.js"
></script>
```

**in React:**

first make sure you have the latest version installed:
```
"@papercups-io/chat-widget": "^1.0.16"
```

```jsx
    <ChatWidget
        // ...
        newMessagePlaceholder='Customize me!', // "Start typing..." by default
        // ...
      />
```

let me know if you need any help or find any issues!

**Comment by BonneauPhilippe** [comment]
Thank you Alex. Do you plan a notification system?

Philippe
 <http://ecommunication.ca/>
Philippe Bonneau

68, route 132

Saint-Germain

G0L 3G0 

581 729-1502
philippe@ecommunication.ca <mailto:philippe@ecommunication.ca> 
Web: ecommunication.ca <http://ecommunication.ca/>
Facebook: ecommunication.kamouraska
 <https://www.facebook.com/ecommunication.kamouraska/>Twitter: eco_mmunication <https://twitter.com/eco_mmunication>
 <https://www.facebook.com/ecommunication.kamouraska/>LinkedIn: philippebonneau <https://ca.linkedin.com/in/philippebonneau>
Skype: philippebonneau

**Comment by reichert621** [comment]
@BonneauPhilippe yes we plan on improving our notifications :)

what kind of notification system would you like?

**Comment by BonneauPhilippe** [comment]
In browser notification, by email, mobile app or SMS. I want to be able to work on other tasks but be notified very quickly when someone writes in the chat. If I can be notified before the user click on the plane icon button would be great.
 <http://ecommunication.ca/>
Philippe Bonneau

68, route 132

Saint-Germain

G0L 3G0 

581 729-1502
philippe@ecommunication.ca <mailto:philippe@ecommunication.ca> 
Web: ecommunication.ca <http://ecommunication.ca/>
Facebook: ecommunication.kamouraska
 <https://www.facebook.com/ecommunication.kamouraska/>Twitter: eco_mmunication <https://twitter.com/eco_mmunication>
 <https://www.facebook.com/ecommunication.kamouraska/>LinkedIn: philippebonneau <https://ca.linkedin.com/in/philippebonneau>
Skype: philippebonneau

**Comment by reichert621** [comment]
@BonneauPhilippe we currently support Slack notifications, and we're working on email next! email should be ready soon

by the way, were you able to fix the "Start typing..." placeholder? can I close this ticket now?

**Comment by BonneauPhilippe** [comment]
Problem solved. Tx
 <http://ecommunication.ca/>
Philippe Bonneau

68, route 132

Saint-Germain

G0L 3G0 

581 729-1502
philippe@ecommunication.ca <mailto:philippe@ecommunication.ca> 
Web: ecommunication.ca <http://ecommunication.ca/>
Facebook: ecommunication.kamouraska
 <https://www.facebook.com/ecommunication.kamouraska/>Twitter: eco_mmunication <https://twitter.com/eco_mmunication>
 <https://www.facebook.com/ecommunication.kamouraska/>LinkedIn: philippebonneau <https://ca.linkedin.com/in/philippebonneau>
Skype: philippebonneau

**Comment by reichert621** [comment]
Feel free to open up another issue if you have anymore questions! Or feel free to email me at alex@papercups.io
