### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by ysfuu** [papercups-io/chat-widget#19]
Hi, I can see that this project uses [theme-ui](https://github.com/system-ui/theme-ui) for it's UI. I think it can easily be ported to the react-native using [theme-ui-native](https://github.com/samjbmason/theme-ui-native). It can be on a separate repo but that would mean maintaining the same codebase twice.

And because there are no native modules for this to work, it can be used with expo too. There are not that many chat products that work on the expo.

**Comment by reichert621** [comment]
great idea @ysfuu! have you tested it out with theme-ui-native to see if it works?

happy to look into this 😄

**Comment by ysfuu** [comment]
I didn't try it but I can't see why it wouldn't work. The differences between the web version and the native version don't seem like a problem for this package.

https://github.com/samjbmason/theme-ui-native#differences-between-theme-ui-for-web-and-theme-ui-for-react-native

**Comment by reichert621** [comment]
hey @ysfuu! we recently added a React Native component if you wanna try it out :) https://github.com/papercups-io/chat-widget-native


(it still needs some tweaks, but you should still be able to play around with it!)
