### ISSUE TITLE
Export ChatWindow component

### ISSUE THREAD

**Issue by fabiosantoscode** [papercups-io/chat-widget#24]
Hello there!

My team is using this module to talk to a custom papercups instance.

We'd like to make sure our users aren't running external code as much as possible, which is why we chose papercups.

However when using this module, we noticed that the window is placed in a separate domain. We'd like to place the `ChatWindow` component within our app code (possibly even using React.lazy and suspense to only load it ondemand much like what the iframe achieved)

The workaround we're currently evaluating is to add this line to the package.json dependencies field:

```
"chat-widget-raw": "papercups-io/chat-widget#0293e84"
```

And include that chat-widget-raw module in our typescript loader configuration.

Is there a plan to expose this component in the future?

Thanks in advance :)

**Comment by reichert621** [comment]
hey @fabiosantoscode! just want to make sure i understand: is your goal to avoid rendering the chat window in an iframe, or would you like to be able to just import the chat window component on its own without the widget toggle etc?

**Comment by fabiosantoscode** [comment]
I would like to avoid loading it from another domain. My preference would be to load it from a subdomain of mine (where I have papercups running).

Rendering it directly from my code as a react component, and controlling the opening logic would be nice but not necessary.

**Comment by fabiosantoscode** [comment]
Sorry for exposing this as an XY problem :)

I want to avoid loading in an iframe -> (tried some stuff without mentioning what I tried) -> so here's how I loaded it directly on my code :)

**Comment by reichert621** [comment]
got it! so basically you want to be able to pass in your own iframe url (e.g. https://github.com/papercups-io/chat-widget/blob/638b52284a6eb8b45dc76786ccaa2aa396fe31a6/src/components/EmbeddableWidget.tsx#L20) and load the chat window from your own (sub)domain -- is that correct?

btw, the code for the chat window is here: https://github.com/papercups-io/chat-window (need to update the docs though 😅 there's a bunch of shared code between the two repos since we started off without an iframe, and then added it to contain things a bit better)

**Comment by fabiosantoscode** [comment]
That's an acceptable solution indeed!

Thanks for sending the link. From what I can see, the app is capable of being `next export` ed which makes serving it on our own that much easier (apps with `[params]` in the URLs aren't exportable to plain old static files).

Currently in our build we already have a find-and-replace step to replace some macros. We could actually start replacing that address with our own, today :)

**Comment by reichert621** [comment]
great! I could also pretty quickly expose a prop if that makes things easier, e.g. `iframeUrlOverride` or something :)

**Comment by fabiosantoscode** [comment]
That would be perfect, I would appreciate it :)

**Comment by fabiosantoscode** [comment]
One note @reichert621: if the iframe's src is somehow not the root of the domain, then the postMessage origin check here will fail:

https://github.com/papercups-io/chat-widget/blob/638b52284a6eb8b45dc76786ccaa2aa396fe31a6/src/components/EmbeddableWidget.tsx#L25

Instead the origin should be compared against new URL(IFRAME_URL).origin

**Comment by reichert621** [comment]
good catch 👍 i'll take that into account

**Comment by reichert621** [comment]
done!
