### ISSUE TITLE
Difficult to find (X) close button

### ISSUE THREAD

**Issue by ivanistheone** [papercups-io/chat-widget#28]
A potential UX issue --- the (X) in the bottom right to close the chat is at an unexpected place

<img width="593" alt="difficult to find close button" src="https://user-images.githubusercontent.com/163966/90838311-923bb080-e322-11ea-9b6c-fca0a6e9b431.png">

I was like "how do I close this?" and kept looking around (my eyes didn't even saccade to the bottom right of the screen as I don't expect actions to be there)

**Comment by reichert621** [comment]
done!
