### ISSUE TITLE
API to raise a ticket through a customized form

### ISSUE THREAD

**Issue by shunkakinoki** [papercups-io/chat-widget#31]
Once again, thanks for amazing work as always.🚀

Is there an API for devs to implement a form for say, raising a ticket?
That would be soooo amazing

**Comment by reichert621** [comment]
hey @shunkakinoki! what do you mean by raising a ticket? like creating a new conversation/message via the API?

**Comment by shunkakinoki** [comment]
hi @reichert621 Thanks once again! 
Yes, for example like creating a ticket through a form like the one below.
If we could have an api to post the form description to papercups, it would really be awesome

example on https://vercel.com/support/request
<img width="1088" alt="Screen Shot 2020-08-27 at 01 05 55" src="https://user-images.githubusercontent.com/39187513/91328156-7ee88380-e801-11ea-95c0-242c1c81a10a.png">

**Comment by reichert621** [comment]
makes sense! I'll have to think about this one a little more... we could make it possible to create a new conversation in papercups through a form like this, but not sure about a "ticketing" system 🤔

**Comment by shunkakinoki** [comment]
Yes definitely! Exactly what I tried to mean thanks for clarifying,
