### ISSUE TITLE
[Question] When will the iframe option be ready?

### ISSUE THREAD

**Issue by shunkakinoki** [papercups-io/chat-widget#32]
I was just curious, being able to implement an iframe on the support page will be so awesome!

**Comment by reichert621** [comment]
hey @shunkakinoki! do you mean so you can embed the chat window on a page without the toggle button?

**Comment by shunkakinoki** [comment]
HI @reichert621 Yes, exactly! Will this be supported? I manually went on the `chat-window` repo link and it led to an iframe-like component, it would be awesome if it was published as a lib too.

**Comment by reichert621** [comment]
I see! Yes we can definitely do this :) would it work for you as an exported React component?

**Comment by shunkakinoki** [comment]
@reichert621 OMG! That would seriously be a game-changer. 

No one literally supports this. Thanks again for being so awesome and supporting niche usecases like ours. You guys really are a doing so much for the internet!!!

**Comment by reichert621** [comment]
no prob! it would actually be easier to do as a React component for now anyway 😛  I'll let you know when it's done!

**Comment by reichert621** [comment]
done (a while ago)!
