### ISSUE TITLE
Cannot read property 'contentWindow' of undefined

### ISSUE THREAD

**Issue by maxbeatty** [papercups-io/chat-widget#40]
I'm using React with react-helmet to include the scripts and getting a lot of errors via Sentry:

> Cannot read property 'contentWindow' of undefined

> undefined is not an object (evaluating 'n.iframeRef.contentWindow')

It looks like it's tracing back to https://github.com/papercups-io/chat-widget/blob/c7e70fda7adbceeba5d122492a18e80d3bca4be8/src/components/EmbeddableWidget.tsx#L238-L240

```jsx
<Helmet>
<script>
        {`
          window.Papercups = {
            config: {
              accountId: 'my-account-id',
              title: 'Welcome!',
              subtitle: 'Ask us anything in the chat window below 😊',
              primaryColor: '#1c64f2',
              greeting: '',
              newMessagePlaceholder: 'Start typing...',
              baseUrl: 'https://app.papercups.io'
            },
          };
        `}
      </script>
      <script
        type="text/javascript"
        async
        defer
        src="https://app.papercups.io/widget.js"
      ></script>
    </Helmet>
```

Does my config look right? Should I switch over to `@papercups-io/chat-widget`?

**Comment by reichert621** [comment]
hey @maxbeatty! can you tell me a little bit more about your setup? (e.g. are you using NextJS or anything like that?)

looks like this is likely a bug on our end, but do you mind trying the `@papercups-io/chat-widget` React component in the meantime to see if that works?

**Comment by maxbeatty** [comment]
Our setup is Gatsby on Firebase almost exactly like [their SEO Component example](https://www.gatsbyjs.com/docs/add-seo-component/#seo-component). I'll try your React component and report back.

**Comment by maxbeatty** [comment]
That looks to have cleared it up.

For anyone else using Gatsby, they'll need to update their `onCreateWebpackConfig` to exclude `@papercups-io/chat-widget` at build time (see detail for trace).

<details><summary>Gatsby Build Error</summary>
WebpackError: TypeError: require is not a function
  
  - incoming_form.js:3 
    node_modules/formidable/lib/incoming_form.js:3:1
  
  - index.js:1 
    node_modules/formidable/lib/index.js:1:20
  
  - index.js:34 
    node_modules/superagent/lib/node/index.js:34:18
  
  - index.modern.js:1 
    node_modules/@papercups-io/chat-widget/dist/index.modern.js:1:1
</details>

```js
exports.onCreateWebpackConfig = ({ stage, actions, getConfig }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      externals: getConfig().externals.concat(function (
        context,
        request,
        callback
      ) {
        const regex = /^@?(firebase|papercups-io)(\/(.+))?/
        // exclude firebase products from being bundled, so they will be loaded using require() at runtime.
        if (regex.test(request)) {
          return callback(null, "umd " + request)
        }
        callback()
      }),
    })
  }
}
```

**Comment by reichert621** [comment]
thanks for sorting this out @maxbeatty! what do you think the best solution would be on our side? is there a bug we ought to fix, or should we just update the docs to mention your discovery?

**Comment by maxbeatty** [comment]
At a glance, you might check that `this.iframeRef` exists before using it. (There's probably consequences I don't understand.) Hard to tell if this is related to Gatsby or Helmet or some combination. 

Thanks for the speedy responses! If it helps you to keep this issue open, please do. Otherwise, everything is working better for me.

**Comment by reichert621** [comment]
no prob! I'm gonna leave this open for now because I still want to dig into this a little, but glad to hear you resolved everything :)

**Comment by maxbeatty** [comment]
This reoccurred and looks like the same code path. Happy to share breadcrumbs privately.

**Comment by reichert621** [comment]
hey @maxbeatty -- sorry for the delay, would love to get more info if you want to email me at alex@papercups.io or ping me on our slack channel! https://github.com/papercups-io/papercups#get-in-touch
