### ISSUE TITLE
Chat content does not display correctly in Firefox

### ISSUE THREAD

**Issue by ivanistheone** [papercups-io/chat-widget#44]
Using Firefox 80.0 (64-bit) on a mac, I try to load the chat widget on [this page](https://nobsmath.com/newlandingpage.htm) and this is what I see:

<img width="866" alt="no chat contents" src="https://user-images.githubusercontent.com/163966/92333161-6b36eb80-f051-11ea-8b27-0e292d5cb1c5.png">

Its weird because the iframe [src URL](https://chat-window.vercel.app/?accountId=c7abdbae-9c0f-4001-bf5a-b82b5778707b&baseUrl=https%3A%2F%2Fapp.papercups.io&greeting=What%27s%20on%20your%20mind%3F&newMessagePlaceholder=Start%20typing...&primaryColor=%2369BC45&requireEmailUpfront=0&subtitle=Ask%20the%20author%20anything...&title=Talk%20to%20us) seems to have the right content when opened in a separate window.

Some more context about js lib versions:

```
yarn list --depth 0 | grep '\(webpack\|paper\|react\)'
├─ @mdx-js/react@1.6.16
├─ @papercups-io/chat-widget@1.0.24
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-plugin-transform-react-display-name@6.25.0
├─ babel-plugin-transform-react-jsx-self@6.22.0
├─ babel-plugin-transform-react-jsx-source@6.22.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ babel-preset-react@6.24.1
├─ extract-text-webpack-plugin@2.1.2
├─ react-dom@16.13.1
├─ react-is@16.13.1
├─ react@16.13.1
├─ webpack-bundle-analyzer@2.13.1
├─ webpack-bundle-tracker@0.2.1
├─ webpack-dev-middleware@1.12.2
├─ webpack-dev-server@2.11.3
├─ webpack-sources@1.3.0
├─ webpack@2.7.0
```

**Comment by ivanistheone** [comment]
nevermind; I updated to `@papercups-io/chat-widget@1.0.29` and it is working fine now

**Comment by reichert621** [comment]
glad to hear it, thanks for letting us know!
