### ISSUE TITLE
Support callback for when chat window opens, closes, and message is sent.

### ISSUE THREAD

**Issue by zkwentz** [papercups-io/chat-widget#49]
I'd like to hook into callbacks for when the chat window is opened, it closes, and when a customer sends a message so that I may push events to Mixpanel / Google Analytics.

**Comment by reichert621** [comment]
good idea! this should be very doable :+1:

btw @zkwentz i'm assuming you're using the react component version of the widget? (as opposed to the html snippet)

**Comment by zkwentz** [comment]
Both actually! I use the snippet on webflow landing page, react component in app.

**Comment by reichert621** [comment]
gotcha, would you like to be able to use callbacks in both? (i was planning on starting off with just adding them to the react component, but happy to do both if you need!)

**Comment by zkwentz** [comment]
Both would be excellent, yes. I'm curious about tracking landing page (e.g. learn about what this app is requests) vs. in-app (e.g. I need help with this app requests) on an aggregate level.

**Comment by reichert621** [comment]
just added! (see bottom of https://github.com/papercups-io/chat-widget#options)

**Comment by zkwentz** [comment]
Thanks, you're fast! Which version should I be on?

**Comment by reichert621** [comment]
ah sorry forgot to mention! `"@papercups-io/chat-widget": "^1.0.33"`

**Comment by zkwentz** [comment]
Thank you for the fast turnaround, and for adding the additional received callback (I was assuming only sent).

**Comment by reichert621** [comment]
no prob!
