### ISSUE TITLE
Allow us to turn off debug messages via prop

### ISSUE THREAD

**Issue by zkwentz** [papercups-io/chat-widget#52]
The debug messages are polluting the console in production. Can we have a prop that lets us turn them off?

**Comment by reichert621** [comment]
yes definitely!

**Comment by reichert621** [comment]
hey @zkwentz -- this is fixed now so that the logs are off by default (unless in a local environment)

fixed in version `"@papercups-io/chat-widget": "^1.0.34"`

(i'll add a prop to opt in to showing logs in production in the near future, but i'm guessing that isn't too urgently needed)
