### ISSUE TITLE
Papercups widget on React no longer working - Element type is invalid

### ISSUE THREAD

**Issue by shea256** [papercups-io/chat-widget#59]
### Server Error

**Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.**

This error happened while generating the page. Any console logs will be displayed in the terminal window.

### Source

```
../../pages/_document.tsx (91:33) @ Function.getInitialProps

  89 |     }
  90 | 
> 91 |     const { html, head } = await ctx.renderPage({ enhanceApp })
     |                                 ^
  92 |     const styles = [...flush()]
  93 |     return { html, head, styles }
  94 |   }
```

### Call Stack

**Function.getInitialProps**

pages/_document.js (5:40)

**Comment by reichert621** [comment]
hey @shea256 -- how are you loading the chat widget currently? and what version are you on?

**Comment by shea256** [comment]
React

    "@papercups-io/chat-widget": "^1.1.0",

**Comment by reichert621** [comment]
@shea256 are you importing like
```
import ChatWidget from '@papercups-io/chat-widget';
```
?

if so, can you try the following:
```
import {ChatWidget} from '@papercups-io/chat-widget';
```

(this may be an issue with NextJS apps, which it looks like you might be using)

**Comment by shea256** [comment]
Ah wow yeah that worked, thanks!

Not sure why it worked originally and then stopped working.

**Comment by reichert621** [comment]
if you updated the version recently, that may have caused it 😓 (we added some updates so that we also export a few other modules, but still need to understand why the default export breaks in NextJS apps)

anyway, glad that fixed it! I'll update the docs to try to make sure no one else has a similar issue 👍

**Comment by shea256** [comment]
OK awesome thanks, sounds good! Will close this issue.
