### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by rosinghal** [papercups-io/chat-widget#62]
I can see `Papercups · Sent 5 hours ago` whenever I open the chat widget (see screenshot attached). I am in IST, so I guess it defaults to GMT.

<img width="383" alt="Screenshot 2020-10-30 at 9 57 55 PM" src="https://user-images.githubusercontent.com/3481438/97783662-4aa59080-1bbf-11eb-9c0d-4b1d575996ae.png">

**Comment by reichert621** [comment]
hey @rosinghal! i think this should be fixed now -- can you double check for me and let me know if I can close this?

**Comment by rosinghal** [comment]
@reichert621 Timezone issue seems to be solved. When looking into this I noticed something else as well, basically, the auto message gets triggered as soon as the website loads, not when the user clicks on the chat icon. Not a very big issue though.
