### ISSUE TITLE
requireEmailUpfront not working

### ISSUE THREAD

**Issue by ressonix** [papercups-io/chat-widget#65]
The requireEmailUpfront option appears not to be working in the latest version available for Heroku Deployment.

**Comment by reichert621** [comment]
hey @ressonix! do you mind providing some more details?

i.e. is the email input not showing up at all? on what page is it not working? etc

**Comment by ressonix** [comment]
Yes, the email field doesn't show up on any page I've tried.

**Comment by reichert621** [comment]
@ressonix are you using our Storytime library as well?

**Comment by ressonix** [comment]
Yes, I am using it. Is there a conflict in using Storytime with it?

**Comment by reichert621** [comment]
it seems like there might be... I'll look into it today 👍

**Comment by reichert621** [comment]
this should be fixed now @ressonix! let me know if you're still seeing issues
