### ISSUE TITLE
Widget scrolling broken in Firefox 82 OSX

### ISSUE THREAD

**Issue by arjenrschat** [papercups-io/chat-widget#67]
Scroll behavior is broken in Firefox due to different way it implements flexbox.
Resulting in a double scrollbar and the window is not auto scrolled to the bottom when a client messages.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/25150192/99545189-6d081e00-29b5-11eb-951b-d5f2ae8f8852.png">

Cause:
#__next, body, html {
    display: flex;
   flex-direction: column;
}

Fix:
#__next{
    display: flex;
   flex-direction: column;
}
body, html {
    display: flex;
   flex-direction: row;
}

Tested in Firefox, Chrome and Safari

**Comment by reichert621** [comment]
thanks @arjenrschat! i think this should be fixed now :) can you verify for me?

**Comment by arjenrschat** [comment]
thanks @reichert621 works great.
