### ISSUE TITLE
Add ability to parse Markdown images

### ISSUE THREAD

**Issue by aguilaair** [papercups-io/chat-widget#90]
Right now if you send an image in markdown (e.g.  `![image](https://i.imgur.com/XC13fLf.png)`) you get an empty message:

![image](https://user-images.githubusercontent.com/29983481/114067019-a0801200-989c-11eb-99bf-d30582d79a8f.png)

Eventhough the papercups backend does not (yet) support uploading images it would be nice to have the ability to send images from a 3rd party service such as Imgur and have them render correctly. This could also be good preparation for when the backend does support images.

**Comment by reichert621** [comment]
will be fixed in the next deploy :)

**Comment by cheeseblubber** [comment]
<img width="396" alt="Screen Shot 2021-04-29 at 2 02 10 PM" src="https://user-images.githubusercontent.com/4218509/116597368-8bbef900-a8f3-11eb-98be-330f69e2529d.png">
